---
# tasks file for docker-registry
- name: login dockerhub
  docker_login:
   username: "eyatrifii"
   password: "baguette22"
   
- name: push image to dockerhub
  docker_image:
   name: devops:latest
   repository: eyatrifii/livraisoncontinue
   push: yes
   source: local
   
