# tasks file for docker
- name: create image docker
  vars:
   ansible_python_interpreter: /usr/bin/python3
  docker_image:
   name: devops
   build:
    path: /var/lib/jenkins/workspace/LivraisonContinue
    pull: no
   source: build
   state: present
   force_source: true
- name: run container docker
  docker_container:
   name: livraisoncontinue_container
   image: devops:latest
   state: started
   recreate: true
   ports:
    - "4200:80"
